import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers";
import SideBar from "../components/Sidebar/Sidebar";
import Header from "@/components/Header/Header";

const poppins = Poppins({ weight: ["500"], subsets: ["devanagari"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <main className="flex justify-start items-start">
            <section className="w-1/5">
              <SideBar />
            </section>
            <section className="w-4/5 p-2 flex flex-col gap-2 h-screen overflow-y-hidden">
              <Header />
              {children}
            </section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
